"""Add progress table

Revision ID: 13c7d7a4a37c
Revises: c5e957651ca8
Create Date: 2025-11-29 16:30:19.499536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c7d7a4a37c'
down_revision = 'c5e957651ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_student_course_progress')
    )
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_progress_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_progress_course_id'))

    op.drop_table('student_progress')
    # ### end Alembic commands ###
