"""Add exercice

Revision ID: 56a72c639996
Revises: a5cc6ac0479b
Create Date: 2025-12-05 15:04:02.272815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56a72c639996'
down_revision = 'a5cc6ac0479b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_exercises_student_id'))
        batch_op.drop_constraint(batch_op.f('exercises_student_id_fkey'), type_='foreignkey')
        batch_op.drop_column('score')
        batch_op.drop_column('feedback')
        batch_op.drop_column('questions')
        batch_op.drop_column('attempt_number')
        batch_op.drop_column('attempt_at')
        batch_op.drop_column('student_id')
        batch_op.drop_column('answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attempt_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('exercises_student_id_fkey'), 'students', ['student_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_exercises_student_id'), ['student_id'], unique=False)
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###
