"""modif

Revision ID: 7c0cb1cc64aa
Revises: be362e07d119
Create Date: 2025-11-28 11:33:48.483079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0cb1cc64aa'
down_revision = 'be362e07d119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))
        batch_op.drop_constraint(batch_op.f('courses_subject_id_fkey'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('courses_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###
