"""Increase branch length and update password_hash

Revision ID: 9f5aca8f24e4
Revises: 56a72c639996
Create Date: 2025-12-13 15:05:28.196346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5aca8f24e4'
down_revision = '56a72c639996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_likes_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_likes_student_id'), ['student_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_student'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_course'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('course_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_course'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student'), 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_course_likes_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_likes_course_id'))

    # ### end Alembic commands ###
