"""modif

Revision ID: be362e07d119
Revises: 45b8aec028dd
Create Date: 2025-11-28 10:45:12.390171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be362e07d119'
down_revision = '45b8aec028dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subjects_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('subjects_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
