"""Add course_explanations table

Revision ID: c5e957651ca8
Revises: 7c0cb1cc64aa
Create Date: 2025-11-28 19:13:22.409137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e957651ca8'
down_revision = '7c0cb1cc64aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_explanations_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_explanations_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_explanations_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_explanations_course_id'))

    op.drop_table('course_explanations')
    # ### end Alembic commands ###
